.\" Copyright (c) 2002 Southern Storm Software, Pty Ltd.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.TH ildb 1 "13 December 2002" "Southern Storm Software" "Portable.NET Development Tools"
.SH NAME
ildb \- the Portable.NET debugger
.SH SYNOPSIS
.ll +8
.B ildb
[ options ]
[ \fIprogram\fR ]
.SH DESCRIPTION
.B Ildb
is used to debug Intermediate Language (IL) applications, using an
interaction style similar to \fBgdb(1)\fR.
.SH "AUTHOR"
Written by Southern Storm Software, Pty Ltd.

http://www.southern-storm.com.au/
.SH "SEE ALSO"
ilrun(1), cscc(1), gdb(1)
.SH "DIAGNOSTICS"
Exit status is 1 if an error occurred while processing the input.
Otherwise the exit status is 0.
.TP
