/*
 * PrintDialog.cs - Implementation of "System.Windows.Forms.PrintDialog" class.
 *
 * Copyright (C) 2004  Southern Storm Software, Pty Ltd.
 * 
 * Autogenerated by csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

using System;
using System.Drawing;
using System.Drawing.Printing;

namespace System.Windows.Forms
{
	[TODO]
	public sealed class PrintDialog : CommonDialog
	{
		[TODO]
		public PrintDialog()
		{
		}

		[TODO]
		public override void Reset()
		{
			throw new NotImplementedException("Reset");
		}

		[TODO]
		protected override bool RunDialog(IntPtr hwndOwner)
		{
			throw new NotImplementedException("RunDialog");
		}

		[TODO]
		public bool AllowPrintToFile 
		{
 			get
			{
				throw new NotImplementedException("AllowPrintToFile");
			}

 			set
			{
				throw new NotImplementedException("AllowPrintToFile");
			}

 		}

		[TODO]
		public bool AllowSelection 
		{
 			get
			{
				throw new NotImplementedException("AllowSelection");
			}

 			set
			{
				throw new NotImplementedException("AllowSelection");
			}

 		}

		[TODO]
		public bool AllowSomePages 
		{
 			get
			{
				throw new NotImplementedException("AllowSomePages");
			}

 			set
			{
				throw new NotImplementedException("AllowSomePages");
			}

 		}

		[TODO]
		public PrintDocument Document 
		{
 			get
			{
				throw new NotImplementedException("Document");
			}

 			set
			{
				throw new NotImplementedException("Document");
			}

 		}

		[TODO]
		public bool PrintToFile 
		{
 			get
			{
				throw new NotImplementedException("PrintToFile");
			}

 			set
			{
				throw new NotImplementedException("PrintToFile");
			}

 		}

		[TODO]
		public PrinterSettings PrinterSettings 
		{
 			get
			{
				throw new NotImplementedException("PrinterSettings");
			}

 			set
			{
				throw new NotImplementedException("PrinterSettings");
			}

 		}

		[TODO]
		public bool ShowHelp 
		{
 			get
			{
				throw new NotImplementedException("ShowHelp");
			}

 			set
			{
				throw new NotImplementedException("ShowHelp");
			}

 		}

		[TODO]
		public bool ShowNetwork 
		{
 			get
			{
				throw new NotImplementedException("ShowNetwork");
			}

 			set
			{
				throw new NotImplementedException("ShowNetwork");
			}

 		}

	}
}//namespace
