/*
 * Debug.cs - Implementation of "System.Diagnostics.Debug" 
 *
 * Copyright (C) 2002  Southern Storm Software, Pty Ltd.
 * Copyright (C) 2002  FSF.
 * 
 * Authors : Autogenerated using csdoc2stub 
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

namespace System.Diagnostics
{
	public sealed class Debug
	{
		[TODO]
		public static void Assert(bool condition)
		{
		/*TODO*/
		}

		[TODO]
		public static void Assert(bool condition, System.String message)
		{
		/*TODO*/
		}

		[TODO]
		public static void Assert(bool condition, System.String message, System.String detailMessage)
		{
		/*TODO*/
		}

		[TODO]
		public static void Close()
		{
		/*TODO*/
		}

		[TODO]
		public static void Fail(System.String message)
		{
		/*TODO*/
		}

		[TODO]
		public static void Fail(System.String message, System.String detailMessage)
		{
		/*TODO*/
		}

		[TODO]
		public static void Flush()
		{
		/*TODO*/
		}

		[TODO]
		public static void Indent()
		{
		/*TODO*/
		}

		[TODO]
		public static void Unindent()
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void Write(System.Object value)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void Write(System.String message)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void Write(System.Object value, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void Write(System.String message, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteIf(bool condition, System.Object value)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteIf(bool condition, System.String message)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteIf(bool condition, System.Object value, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteIf(bool condition, System.String message, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLine(System.Object value)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLine(System.String message)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLine(System.Object value, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLine(System.String message, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLineIf(bool condition, System.Object value)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLineIf(bool condition, System.String message)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLineIf(bool condition, System.Object value, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		[Conditional("DEBUG")]
		public static void WriteLineIf(bool condition, System.String message, System.String category)
		{
		/*TODO*/
		}

		[TODO]
		public static bool AutoFlush 
		{ 
			get
			{
				return false;
			} 
			set
			{
			} 
		}

		[TODO]
		public static int IndentLevel 
		{ 
			get
			{
				return 0;
			}
			set
			{
			}
		}

		[TODO]
		public static int IndentSize 
		{
			get
			{
				return 4;
			}
			set
			{
			}
		}
	}
}//namespace
