/*
 * opcodes.c - Opcode information tables.
 *
 * Copyright (C) 2001  Southern Storm Software, Pty Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#include "il_opcodes.h"

#ifdef	__cplusplus
extern	"C" {
#endif

ILOpcodeInfo const ILMainOpcodeTable[256] = {
	{"nop",				0, 0, IL_OPCODE_ARGS_NONE, 1},
	{"break",			0, 0, IL_OPCODE_ARGS_INVALID, 1},

	{"ldarg.0",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldarg.1",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldarg.2",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldarg.3",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldloc.0",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldloc.1",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldloc.2",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldloc.3",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"stloc.0",			1, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stloc.1",			1, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stloc.2",			1, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stloc.3",			1, 0, IL_OPCODE_ARGS_NONE, 1},

	{"ldarg.s",			0, 1, IL_OPCODE_ARGS_SHORT_ARG, 2},
	{"ldarga.s",		0, 1, IL_OPCODE_ARGS_SHORT_ARG, 2},
	{"starg.s",			1, 0, IL_OPCODE_ARGS_SHORT_ARG, 2},
	{"ldloc.s",			0, 1, IL_OPCODE_ARGS_SHORT_VAR, 2},
	{"ldloca.s",		0, 1, IL_OPCODE_ARGS_SHORT_VAR, 2},
	{"stloc.s",			1, 0, IL_OPCODE_ARGS_SHORT_VAR, 2},

	{"ldnull",			0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.m1",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.0",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.1",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.2",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.3",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.4",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.5",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.6",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.7",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.8",		0, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldc.i4.s",		0, 1, IL_OPCODE_ARGS_INT8, 2},
	{"ldc.i4",			0, 1, IL_OPCODE_ARGS_INT32, 5},
	{"ldc.i8",			0, 1, IL_OPCODE_ARGS_INT64, 9},
	{"ldc.r4",			0, 1, IL_OPCODE_ARGS_FLOAT32, 5},
	{"ldc.r8",			0, 1, IL_OPCODE_ARGS_FLOAT64, 9},

	{"ldptr",			0, 1, IL_OPCODE_ARGS_INT32 | IL_OPCODE_ARGS_UNSAFE, 5},

	{"dup",				1, 2, IL_OPCODE_ARGS_NONE, 1},
	{"pop",				1, 0, IL_OPCODE_ARGS_NONE, 1},

	{"jmp",				0, 0, IL_OPCODE_ARGS_CALL, 5},
	{"call",			0, 0, IL_OPCODE_ARGS_CALL, 5},
	{"calli",			0, 0, IL_OPCODE_ARGS_CALLI, 5},
	{"ret",				0, 0, IL_OPCODE_ARGS_NONE, 1},

	{"br.s",			0, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"brfalse.s",		1, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"brtrue.s",		1, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"beq.s",			2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"bge.s",			2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"bgt.s",			2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"ble.s",			2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"blt.s",			2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"bne.un.s",		2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"bge.un.s",		2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"bgt.un.s",		2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"ble.un.s",		2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"blt.un.s",		2, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},
	{"br",				0, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"brfalse",			1, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"brtrue",			1, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"beq",				2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"bge",				2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"bgt",				2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"ble",				2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"blt",				2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"bne.un",			2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"bge.un",			2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"bgt.un",			2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"ble.un",			2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"blt.un",			2, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},

	{"switch",			1, 0, IL_OPCODE_ARGS_SWITCH, 0},

	{"ldind.i1",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.u1",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.i2",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.u2",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.i4",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.u4",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.i8",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.i",			1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.r4",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.r8",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"ldind.ref",		1, 1, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.ref",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.i1",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.i2",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.i4",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.i8",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.r4",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},
	{"stind.r8",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},

	{"add",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"sub",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"mul",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"div",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"div.un",			2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"rem",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"rem.un",			2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"and",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"or",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"xor",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"shl",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"shr",				2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"shr.un",			2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"neg",				1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"not",				1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"conv.i1",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.i2",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.i4",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.i8",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.r4",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.r8",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.u4",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.u8",			1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"callvirt",		0, 0, IL_OPCODE_ARGS_CALLVIRT, 5},
	{"cpobj",			2, 0, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldobj",			1, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldstr",			0, 1, IL_OPCODE_ARGS_STRING, 5},

	{"newobj",			0, 1, IL_OPCODE_ARGS_NEW, 5},
	{"castclass",		1, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"isinst",			1, 1, IL_OPCODE_ARGS_TOKEN, 5},

	{"conv.r.un",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ann.data.s",		0, 0, IL_OPCODE_ARGS_ANN_DATA, 0},

	{"unused_78",		0, 0, IL_OPCODE_ARGS_INVALID, 1},

	{"unbox",			1, 1, IL_OPCODE_ARGS_TOKEN, 5},

	{"throw",			1, 0, IL_OPCODE_ARGS_NONE, 1},

	{"ldfld",			1, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldflda",			1, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"stfld",			2, 0, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldsfld",			0, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldsflda",			0, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"stsfld",			1, 0, IL_OPCODE_ARGS_TOKEN, 5},
	{"stobj",			2, 0, IL_OPCODE_ARGS_TOKEN, 5},

	{"conv.ovf.i1.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i2.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i4.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i8.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u1.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u2.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u4.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u8.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u.un",	1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"box",				1, 1, IL_OPCODE_ARGS_TOKEN, 5},

	{"newarr",			1, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldlen",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelema",			2, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"ldelem.i1",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.u1",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.i2",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.u2",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.i4",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.u4",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.i8",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.i",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.r4",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.r8",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"ldelem.ref",		2, 1, IL_OPCODE_ARGS_NONE, 1},

	{"stelem.i",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.i1",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.i2",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.i4",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.i8",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.r4",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.r8",		3, 0, IL_OPCODE_ARGS_NONE, 1},
	{"stelem.ref",		3, 0, IL_OPCODE_ARGS_NONE, 1},

	{"unused_A3",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_A4",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_A5",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_A6",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_A7",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_A8",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_A9",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_AA",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_AB",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_AC",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_AD",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_AE",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_AF",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_B0",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_B1",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_B2",		0, 0, IL_OPCODE_ARGS_INVALID, 1},

	{"conv.ovf.i1",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u1",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i2",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u2",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i4",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u4",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i8",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u8",		1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"unused_BB",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_BC",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_BD",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_BE",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_BF",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_C0",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_C1",		0, 0, IL_OPCODE_ARGS_INVALID, 1},

	{"refanyval",		1, 1, IL_OPCODE_ARGS_TOKEN, 5},
	{"ckfinite",		1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"unused_C4",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_C5",		0, 0, IL_OPCODE_ARGS_INVALID, 1},

	{"mkrefany",		1, 1, IL_OPCODE_ARGS_TOKEN, 5},

	{"ann.call",		0, 0, IL_OPCODE_ARGS_TOKEN, 5},
	{"ann.catch",		0, 0, IL_OPCODE_ARGS_NONE, 1},
	{"ann.dead",		0, 0, IL_OPCODE_ARGS_ANN_DEAD, 3},
	{"ann.hoisted",		0, 0, IL_OPCODE_ARGS_NONE, 1},
	{"ann.hoisted_call",0, 0, IL_OPCODE_ARGS_TOKEN, 5},
	{"ann.lab",			0, 0, IL_OPCODE_ARGS_NONE, 1},
	{"ann.def",			0, 0, IL_OPCODE_ARGS_NONE, 1},
	{"ann.ref.s",		0, 0, IL_OPCODE_ARGS_ANN_REF, 2},
	{"ann.phi",			0, 0, IL_OPCODE_ARGS_ANN_PHI, 0},

	{"ldtoken",			0, 1, IL_OPCODE_ARGS_TOKEN, 5},

	{"conv.u2",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.u1",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.i",			1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.i",		1, 1, IL_OPCODE_ARGS_NONE, 1},
	{"conv.ovf.u",		1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"add.ovf",			2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"add.ovf.un",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"mul.ovf",			2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"mul.ovf.un",		2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"sub.ovf",			2, 1, IL_OPCODE_ARGS_NONE, 1},
	{"sub.ovf.un",		2, 1, IL_OPCODE_ARGS_NONE, 1},

	{"endfinally",		0, 0, IL_OPCODE_ARGS_NONE, 1},

	{"leave",			0, 0, IL_OPCODE_ARGS_LONG_JUMP, 5},
	{"leave.s",			0, 0, IL_OPCODE_ARGS_SHORT_JUMP, 2},

	{"stdind.i",		2, 0, IL_OPCODE_ARGS_NONE | IL_OPCODE_ARGS_UNSAFE, 1},

	{"conv.u",			1, 1, IL_OPCODE_ARGS_NONE, 1},

	{"unused_E1",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E2",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E3",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E4",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E5",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E6",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E7",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E8",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_E9",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_EA",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_EB",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_EC",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_ED",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_EE",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_EF",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F0",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F1",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F2",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F3",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F4",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F5",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F6",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F7",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F8",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_F9",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_FA",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_FB",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_FC",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
	{"unused_FD",		0, 0, IL_OPCODE_ARGS_INVALID, 1},

	{"prefix",			0, 0, IL_OPCODE_ARGS_INVALID, 0},

	{"unused_FF",		0, 0, IL_OPCODE_ARGS_INVALID, 1},
};

ILOpcodeInfo const ILPrefixOpcodeTable[256] = {
	{"arglist",				0, 1, IL_OPCODE_ARGS_NONE, 2},

	{"ceq",					2, 1, IL_OPCODE_ARGS_NONE, 2},
	{"cgt",					2, 1, IL_OPCODE_ARGS_NONE, 2},
	{"cgt.un",				2, 1, IL_OPCODE_ARGS_NONE, 2},
	{"clt",					2, 1, IL_OPCODE_ARGS_NONE, 2},
	{"clt.un",				2, 1, IL_OPCODE_ARGS_NONE, 2},

	{"ldftn",				0, 1, IL_OPCODE_ARGS_TOKEN, 6},
	{"ldvirtftn",			1, 1, IL_OPCODE_ARGS_TOKEN, 6},

	{"jmpi",				1, 0, IL_OPCODE_ARGS_CALLI, 6},

	{"ldarg",				0, 1, IL_OPCODE_ARGS_LONG_VAR, 4},
	{"ldarga",				0, 1, IL_OPCODE_ARGS_LONG_VAR, 4},
	{"starg",				1, 0, IL_OPCODE_ARGS_LONG_VAR, 4},
	{"ldloc",				0, 1, IL_OPCODE_ARGS_LONG_VAR, 4},
	{"ldloca",				0, 1, IL_OPCODE_ARGS_LONG_VAR, 4},
	{"stloc",				1, 0, IL_OPCODE_ARGS_LONG_VAR, 4},

	{"localloc",			1, 1, IL_OPCODE_ARGS_NONE, 2},

	{"unused_prefix_10",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"endfilter",			1, 0, IL_OPCODE_ARGS_NONE, 2},
	{"unaligned.",			0, 0, IL_OPCODE_ARGS_UINT8, 3},
	{"volatile.",			0, 0, IL_OPCODE_ARGS_NONE, 2},
	{"tail.",				0, 0, IL_OPCODE_ARGS_NONE, 2},
	{"initobj",				1, 0, IL_OPCODE_ARGS_TOKEN, 6},
	{"ann.live",			0, 0, IL_OPCODE_ARGS_ANN_LIVE, 4},
	{"cpblk",				3, 0, IL_OPCODE_ARGS_NONE, 2},
	{"initblk",				3, 0, IL_OPCODE_ARGS_NONE, 2},
	{"ann.ref",				0, 0, IL_OPCODE_ARGS_ANN_REF, 4},
	{"rethrow",				0, 0, IL_OPCODE_ARGS_NONE, 2},

	{"unused_prefix_1B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"sizeof",				0, 1, IL_OPCODE_ARGS_TOKEN, 6},
	{"refanytype",			1, 1, IL_OPCODE_ARGS_NONE, 2},

	{"unused_prefix_1E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_1F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_20",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_21",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"ann.data",			0, 0, IL_OPCODE_ARGS_ANN_DATA, 0},
	{"ann.arg",				0, 0, IL_OPCODE_ARGS_ANN_ARG, 4},

	{"unused_prefix_24",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_25",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_26",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_27",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_28",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_29",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_2A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_2B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_2C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_2D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_2E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_2F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_30",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_31",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_32",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_33",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_34",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_35",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_36",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_37",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_38",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_39",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_3A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_3B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_3C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_3D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_3E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_3F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_40",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_41",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_42",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_43",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_44",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_45",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_46",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_47",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_48",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_49",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_4A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_4B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_4C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_4D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_4E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_4F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_50",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_51",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_52",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_53",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_54",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_55",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_56",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_57",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_58",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_59",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_5A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_5B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_5C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_5D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_5E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_5F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_60",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_61",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_62",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_63",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_64",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_65",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_66",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_67",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_68",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_69",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_6A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_6B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_6C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_6D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_6E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_6F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_70",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_71",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_72",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_73",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_74",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_75",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_76",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_77",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_78",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_79",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_7A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_7B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_7C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_7D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_7E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_7F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_80",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_81",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_82",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_83",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_84",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_85",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_86",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_87",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_88",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_89",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_8A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_8B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_8C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_8D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_8E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_8F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_90",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_91",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_92",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_93",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_94",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_95",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_96",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_97",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_98",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_99",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_9A",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_9B",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_9C",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_9D",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_9E",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_9F",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_A0",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A1",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A2",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A3",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A4",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A5",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A6",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A7",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A8",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_A9",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_AA",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_AB",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_AC",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_AD",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_AE",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_AF",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_B0",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B1",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B2",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B3",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B4",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B5",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B6",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B7",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B8",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_B9",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_BA",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_BB",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_BC",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_BD",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_BE",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_BF",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_C0",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C1",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C2",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C3",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C4",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C5",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C6",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C7",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C8",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_C9",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_CA",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_CB",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_CC",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_CD",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_CE",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_CF",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_D0",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D1",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D2",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D3",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D4",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D5",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D6",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D7",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D8",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_D9",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_DA",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_DB",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_DC",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_DD",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_DE",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_DF",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_E0",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E1",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E2",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E3",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E4",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E5",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E6",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E7",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E8",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_E9",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_EA",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_EB",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_EC",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_ED",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_EE",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_EF",	0, 0, IL_OPCODE_ARGS_INVALID, 2},

	{"unused_prefix_F0",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F1",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F2",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F3",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F4",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F5",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F6",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F7",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F8",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_F9",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_FA",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_FB",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_FC",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_FD",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_FE",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
	{"unused_prefix_FF",	0, 0, IL_OPCODE_ARGS_INVALID, 2},
};

#ifdef	__cplusplus
};
#endif
